title: Ondeando
description: meu proto-jardim-digital, um espaço para ficar mais distante das mídias-sociais, feeds infinitos e algorítmos malvados.
url: "https://pedro.dalbo.me"
author: dalbo1201

markdown: kramdown
highlighter: rouge

permalink: /blog/:slug/
future: false
timezone: America/Sao_Paulo

plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  collection: posts
  per_page: 7
  title: ':title - página :num'
  permalink: /page/:num/
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

defaults:
  - scope:
      path: ""
      type: posts
    values:
      permalink: /blog/:slug/
  - scope:
      path: "tags"
      type: pages
    values:
      permalink: /tags/:slug/

exclude:
  - README.md
  - LICENSE.md
